# config/services/annotations.yaml
services:
  annotation_reader:
    class: Doctrine\Common\Annotations\AnnotationReader
    public: false

  Doctrine\Common\Annotations\AnnotationReader:
    alias: annotation_reader
